VARIABLE:SS:=0;

TT:VALUEWHEN(CROSSDOWN(BKVOL,0.5)||CROSSDOWN(SKVOL,0.5),MONEYTOT),NODRAW;

IF BARPOS=1 THEN
SS:=1;

IF MONEYTOT>HV(TT,0)&&BKVOL+SKVOL=0 THEN
SS:=1;

IF (CROSSDOWN(BKVOL,0.5)||CROSSDOWN(SKVOL,0.5))&&MONEYTOT<=HV(TT,0) THEN
SS:=SS+1;
MM:SS,NODRAW, COLORYELLOW;
SS:=1;
//以上是资金管理模块

KNUM:=COUNT(C>0,0);
初始:REF(MONEYREAL/10000,KNUM-1),NODRAW;
当前..MONEYREAL/10000,COLORCYAN;
QYMA..EMA(当前, 12),COLORYELLOW,LINETHICK3;
最小..LV(当前,0);
最大..HV(当前,0),COLORGREEN,LINETHICK3;

DANGRI:=BARSLAST(DATE<>REF(DATE,1));

FANSHOU:=1;
QBP:=LASTSIG=201;
QBK:=LASTSIG<>201;
QSP:=LASTSIG=200;
QSK:=LASTSIG<>200;

RSV:=(C-LLV(L,63))/(HHV(H,63)-LLV(L,63))*100;
K:=SMA(RSV,18,1);
MAA:=EMA(C,255);
AA:=ABS(C-REF(C,1))>=REF(HHV(ABS(H-L),35),1);
AA2:=ABS(C-REF(C,2))>=REF(HHV(ABS(C-REF(C,2)),35),1);


 (C>MAA AND K<48 AND ISUP AND (AA OR AA2) AND BARSSK>109) AND FANSHOU=0 AND QBP,BP(SKVOL);
 (C>MAA AND K<48 AND ISUP AND (AA OR AA2) AND BARSSK>109) AND FANSHOU=0 AND QBK,BK(SS);
 (C>MAA AND K<48 AND ISUP AND (AA OR AA2) AND BARSSK>109) AND FANSHOU=1,BPK(SS);
 (C<MAA AND K<48 AND ISUP AND (AA OR AA2) AND BARSSK>109) AND QBP,BP(SKVOL);

 (C<MAA AND K>39 AND ISDOWN AND (AA OR AA2) AND BARSBK>50) AND FANSHOU=0 AND QSP,SP(BKVOL);
 (C<MAA AND K>39 AND ISDOWN AND (AA OR AA2) AND BARSBK>50) AND FANSHOU=0 AND QSK,SK(SS);
 (C<MAA AND K>39 AND ISDOWN AND (AA OR AA2) AND BARSBK>50) AND FANSHOU=1,SPK(SS);
 (C>MAA AND K>39 AND ISDOWN AND (AA OR AA2) AND BARSBK>50) AND QSP,SP(BKVOL);

TMP:=STD(O+C,93)/2;
OO:=VALUEWHEN(DATE<>REF(DATE,1),O);
CC:=VALUEWHEN(DATE<>REF(DATE,1),C);
BB:=MAX(OO,CC)+0.1*5*TMP;
DD:=MIN(OO,CC)-0.1*5*TMP;

 (C>MAA AND K<48 AND C>REF(C,1) AND (C>BB AND C>SKPRICE)) AND FANSHOU=0 AND QBP,BP(SKVOL);
 (C>MAA AND K<48 AND C>REF(C,1) AND (C>BB AND C>SKPRICE)) AND FANSHOU=0 AND QBK,BK(SS);
 (C>MAA AND K<48 AND C>REF(C,1) AND (C>BB AND C>SKPRICE)) AND FANSHOU=1,BPK(SS);

 (C<MAA AND K>39 AND C<REF(C,1) AND (C<DD AND C<BKPRICE)) AND FANSHOU=0 AND QSP,SP(BKVOL);
 (C<MAA AND K>39 AND C<REF(C,1) AND (C<DD AND C<BKPRICE)) AND FANSHOU=0 AND QSK,SK(SS);
 (C<MAA AND K>39 AND C<REF(C,1) AND (C<DD AND C<BKPRICE)) AND FANSHOU=1,SPK(SS);

RC:=C/REF(C,1);
ARC:=SMA(REF(RC,1),177,1);
MA1:=MA(C,85);
MA2:=MA(C,190);

 (CROSS(MA1,MA2) AND ARC>1) AND FANSHOU=0 AND QBP,BP(SKVOL);
 (CROSS(MA1,MA2) AND ARC>1) AND FANSHOU=0 AND QBK,BK(SS);
 (CROSS(MA1,MA2) AND ARC>1) AND FANSHOU=1,BPK(SS);
 (CROSS(MA2,MA1) AND ARC<1) AND FANSHOU=0 AND QSP,SP(BKVOL);
 (CROSS(MA2,MA1) AND ARC<1) AND FANSHOU=0 AND QSK,SK(SS);
 (CROSS(MA2,MA1) AND ARC<1) AND FANSHOU=1,SPK(SS);

VAR1:=(2*C+H+L)/4;
VAR2:=LLV(L,63);
VAR3:=HHV(H,63);
ZL:=EMA((VAR1-VAR2)/(VAR3-VAR2)*100,373);
SH:=EMA(0.7*REF(ZL,1)+0.3*ZL,118);

 (CROSS(ZL,SH) AND SH>54) AND FANSHOU=0 AND QBP,BP(SKVOL);
 (CROSS(ZL,SH) AND SH>54) AND FANSHOU=0 AND QBK,BK(SS);
 (CROSS(ZL,SH) AND SH>54) AND FANSHOU=1,BPK(SS);
 (CROSS(SH,ZL) AND ZL<45) AND FANSHOU=0 AND QSP,SP(BKVOL);
 (CROSS(SH,ZL) AND ZL<45) AND FANSHOU=0 AND QSK,SK(SS);
 (CROSS(SH,ZL) AND ZL<45) AND FANSHOU=1,SPK(SS);
 (CROSS(ZL,SH) AND SH<48) AND FANSHOU=0 AND QBP,BP(SKVOL);
 (CROSS(ZL,SH) AND SH<48) AND FANSHOU=0 AND QBK,BK(SS);
 (CROSS(ZL,SH) AND SH<48) AND FANSHOU=1,BPK(SS);
 (CROSS(SH,ZL) AND ZL>72) AND FANSHOU=0 AND QSP,SP(BKVOL);
 (CROSS(SH,ZL) AND ZL>72) AND FANSHOU=0 AND QSK,SK(SS);
 (CROSS(SH,ZL) AND ZL>72) AND FANSHOU=1,SPK(SS);

MAB:=EMA(C,109);
RSV2:=(C-LLV(L,3))/(HHV(H,3)-LLV(L,3))*100;
KK:=SMA(RSV2,59,1);
DD2:=SMA(KK,105,1);

(CROSS(KK,DD2) AND DD2<1 AND MAB>REF(MAB,1)) AND FANSHOU=0 AND QBP,BP(SKVOL);
 (CROSS(KK,DD2) AND DD2<1 AND MAB>REF(MAB,1)) AND FANSHOU=0 AND QBK,BK(SS);
 (CROSS(KK,DD2) AND DD2<1 AND MAB>REF(MAB,1)) AND FANSHOU=1,BPK(SS);
 (CROSS(DD2,KK) AND DD2>47 AND MAB<REF(MAB,1)) AND FANSHOU=0 AND QSP,SP(BKVOL);
 (CROSS(DD2,KK) AND DD2>47 AND MAB<REF(MAB,1)) AND FANSHOU=0 AND QSK,SK(SS);
 (CROSS(DD2,KK) AND DD2>47 AND MAB<REF(MAB,1)) AND FANSHOU=1,SPK(SS);

 C<(1-0.001*34)*BKPRICE,SP(BKVOL);
 C>(1+0.001*48)*SKPRICE,BP(SKVOL);
 C>(1+0.001*272)*BKPRICE,SP(BKVOL);
 C<(1-0.001*95)*SKPRICE,BP(SKVOL);

SETSIGPRICETYPE(BK,LIMIT_ORDER);
SETSIGPRICETYPE(SK,LIMIT_ORDER);
SETSIGPRICETYPE(BP,LIMIT_ORDER);
SETSIGPRICETYPE(SP,LIMIT_ORDER);
SETSIGPRICETYPE(BPK,LIMIT_ORDER);
SETSIGPRICETYPE(SPK,LIMIT_ORDER);
SETSIGPRICETYPE(CLOSEOUT,LIMIT_ORDER);

SIGNOW..LASTSIG,NODRAW;


/*
LASTSIG判断最近一个信号

注：由BPK指令产生的BK信号按BPK信号处理，SPK指令产生的SK信号同理。

例：AA:LASTSIG=BK;//最近一个 稳定的信号为BK信号AA返回值为1，否则返回0.
LASTSIG的不同返回值代表的信号：
BK:200;
SK:201;
BP:202;
SP:203;
BPK:204;
SPK:205;
CLOSEOUT:206;
STOP:207;
//TRADE_OTHER('AUTO');

//行情中寻找阶段高低点，在低点进场做多，高点进场做空，但是这些高低点都是波浪的一浪和二浪的回撤低点，不是逆势接单。下单采用市价，不用客户自己设置成交点位，程序会自动换月，需要把螺纹指数和螺纹主力的15分钟数据下载完全，加载到螺纹15分指数上。
*/